[versions]
agp = "8.9.3"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
playServiceLocation = "21.3.0"
playServiceMaps = "19.2.0"
maps_composeVersion = "1.0.0"
mapsSecret = "2.0.1"
retrofitVersion = "2.9.0"
converter_gsonVersion = "2.9.0"
kotlinx_coroutines_androidVersion = "1.7.3"
firebaseStorageKtx = "22.0.1"
fragment = "1.8.9"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
play-services-location ={group="com.google.android.gms", name = "play-services-location", version.ref = "playServiceLocation"}
maps-compose = {group  ="com.google.maps.android", name="maps-compose", version.ref = "maps_composeVersion"}
play-services-maps = {group = "com.google.android.gms", name = "play-services-maps", version.ref="playServiceMaps"}
retrofit = {group = "com.squareup.retrofit2", name ="retrofit", version.ref = "retrofitVersion" }
converter-gson = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converter_gsonVersion"}
kotlinx-coroutines-android = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx_coroutines_androidVersion"}
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maps-secret = {id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref="mapsSecret"}

